# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_picker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_activeHoursPicker(object):
    def setupUi(self, activeHoursPicker):
        activeHoursPicker.setObjectName("activeHoursPicker")
        activeHoursPicker.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(activeHoursPicker)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.activeHoursPickerVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.activeHoursPickerVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.activeHoursPickerVerticalLayout.setObjectName("activeHoursPickerVerticalLayout")
        self.activeHoursPickerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.activeHoursPickerLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.activeHoursPickerLabel.setObjectName("activeHoursPickerLabel")
        self.activeHoursPickerVerticalLayout.addWidget(self.activeHoursPickerLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.startTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startTimeLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startTimeHour = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.startTimeHour.setMinimum(1)
        self.startTimeHour.setMaximum(12)
        self.startTimeHour.setObjectName("startTimeHour")
        self.horizontalLayout.addWidget(self.startTimeHour)
        self.startTimeColon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.startTimeColon.setMaximumSize(QtCore.QSize(2, 16777215))
        self.startTimeColon.setAlignment(QtCore.Qt.AlignCenter)
        self.startTimeColon.setObjectName("startTimeColon")
        self.horizontalLayout.addWidget(self.startTimeColon)
        self.startTimeMinute = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.startTimeMinute.setPrefix("")
        self.startTimeMinute.setMaximum(59)
        self.startTimeMinute.setObjectName("startTimeMinute")
        self.horizontalLayout.addWidget(self.startTimeMinute)
        self.startTimeAPM = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.startTimeAPM.setObjectName("startTimeAPM")
        self.startTimeAPM.addItem("")
        self.startTimeAPM.addItem("")
        self.horizontalLayout.addWidget(self.startTimeAPM)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.endTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.endTimeLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.endTimeHour = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.endTimeHour.setMinimum(1)
        self.endTimeHour.setMaximum(12)
        self.endTimeHour.setObjectName("endTimeHour")
        self.horizontalLayout_2.addWidget(self.endTimeHour)
        self.endTimeColon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.endTimeColon.setMaximumSize(QtCore.QSize(2, 16777215))
        self.endTimeColon.setAlignment(QtCore.Qt.AlignCenter)
        self.endTimeColon.setObjectName("endTimeColon")
        self.horizontalLayout_2.addWidget(self.endTimeColon)
        self.endTimeMinute = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.endTimeMinute.setObjectName("endTimeMinute")
        self.horizontalLayout_2.addWidget(self.endTimeMinute)
        self.endTimeAPM = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.endTimeAPM.setObjectName("endTimeAPM")
        self.endTimeAPM.addItem("")
        self.endTimeAPM.addItem("")
        self.horizontalLayout_2.addWidget(self.endTimeAPM)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.activeHoursPickerVerticalLayout.addLayout(self.formLayout)
        self.activeHoursPickerButtonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.activeHoursPickerButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.activeHoursPickerButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.activeHoursPickerButtonBox.setObjectName("activeHoursPickerButtonBox")
        self.activeHoursPickerVerticalLayout.addWidget(self.activeHoursPickerButtonBox)

        self.retranslateUi(activeHoursPicker)
        self.activeHoursPickerButtonBox.accepted.connect(activeHoursPicker.accept) # type: ignore
        self.activeHoursPickerButtonBox.rejected.connect(activeHoursPicker.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(activeHoursPicker)

    def retranslateUi(self, activeHoursPicker):
        _translate = QtCore.QCoreApplication.translate
        activeHoursPicker.setWindowTitle(_translate("activeHoursPicker", "Dialog"))
        self.activeHoursPickerLabel.setText(_translate("activeHoursPicker", "Select Active Hours"))
        self.startTimeLabel.setText(_translate("activeHoursPicker", "Start at"))
        self.startTimeColon.setText(_translate("activeHoursPicker", ":"))
        self.startTimeAPM.setCurrentText(_translate("activeHoursPicker", "AM"))
        self.startTimeAPM.setItemText(0, _translate("activeHoursPicker", "AM"))
        self.startTimeAPM.setItemText(1, _translate("activeHoursPicker", "PM"))
        self.endTimeLabel.setText(_translate("activeHoursPicker", "End at"))
        self.endTimeColon.setText(_translate("activeHoursPicker", ":"))
        self.endTimeAPM.setItemText(0, _translate("activeHoursPicker", "AM"))
        self.endTimeAPM.setItemText(1, _translate("activeHoursPicker", "PM"))
